name: 'javaapp'

services:
  db:
    image: postgres:14.12-alpine
    restart: always
    container_name: javaapp-db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - javaapp-network
  
  api:
    container_name: javaapp-api
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://javaapp-db/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - javaapp-network
    depends_on:
      - db

networks:
    javaapp-network:
        driver: bridge

